public enum Suction //���� �� �������
{
    EnsureSceneSafety,
    WearPPE,
    CheckEquipmentAndSupplies,
    TurnOnSuctionDevice,
    CheckSuctionPressure,
    TestSuctionWithSaline,
    PerformOralSuction,
    FlushSuctionTipWithSaline,
    TurnOffSuctionDevice,
    AssembleOxygenTankAndRegulator,
    OpenOxygenTankValve,
    CheckForLeaksAndStateNoLeaks,
    CheckOxygenGaugeAndStateRemainingPressure,
    ConnectNonRebreatherMask,
    SetOxygenFlowRate,
    FillReservoirBagAndApplyMask,
    MonitorPatientRespiration,
    RemoveMaskUponInstruction,
    TurnOffFlowMeterAndTank,
    RecordOnMedicalChart
}
